<a href="https://colab.research.google.com/github/raulantonoo/coba/blob/main/DataMining.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
dataset = pd.read_csv('Buku.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [ ]:
print(x)

[['Semarang' 120.0 nan]
 ['Surabaya' 140.0 21000000.0]
 ['Bekasi' 130.0 31000000.0]
 ['Bandung' nan 61000000.0]
 ['Kalimantan' 140.0 21000000.0]
 ['Sumatra' 135.0 58000000.0]]


In [ ]:
print(y)

['Tidak' 'Ya' 'Tidak' 'Tidak' 'Ya' 'Ya']


In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [ ]:
print(x)

[['Semarang' 120.0 38400000.0]
 ['Surabaya' 140.0 21000000.0]
 ['Bekasi' 130.0 31000000.0]
 ['Bandung' 133.0 61000000.0]
 ['Kalimantan' 140.0 21000000.0]
 ['Sumatra' 135.0 58000000.0]]


In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder = 'passthrough')
x = np.array(ct.fit_transform(x))

In [ ]:
print(x)

[[0.0 0.0 0.0 1.0 0.0 0.0 120.0 38400000.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 140.0 21000000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 130.0 31000000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 133.0 61000000.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 140.0 21000000.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 135.0 58000000.0]]


In [ ]:
print(y)

['Tidak' 'Ya' 'Tidak' 'Tidak' 'Ya' 'Ya']


In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [ ]:
print(y)

[0 1 0 0 1 1]


In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [ ]:
print(x_train)

[[0.0 0.0 1.0 0.0 0.0 0.0 140.0 21000000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 120.0 38400000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 133.0 61000000.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 135.0 58000000.0]]


In [ ]:
print(x_test)

[[0.0 1.0 0.0 0.0 0.0 0.0 130.0 31000000.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 140.0 21000000.0]]


In [ ]:
print(y_train)

[1 0 0 1]


In [ ]:
print(y_test)

[0 1]


In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [ ]:
print(x_train)

[[0.0 0.0 1.0 -0.5773502691896258 -0.5773502691896258 0.0
  1.0836567383657543 -1.4608592996857799]
 [0.0 0.0 0.0 1.7320508075688774 -0.5773502691896258 0.0
  -1.6254851075486312 -0.3837850702564337]
 [1.0 0.0 0.0 -0.5773502691896258 -0.5773502691896258 0.0
  0.13545709229571928 1.0151734116460505]
 [0.0 0.0 0.0 -0.5773502691896258 1.7320508075688774 0.0
  0.4063712768871578 0.8294709582961632]]


In [ ]:
print(x_test)

[[0.0 1.0 0.0 -0.5773502691896258 -0.5773502691896258 0.0
  -0.27091418459143857 -0.8418511218528224]
 [0.0 0.0 0.0 -0.5773502691896258 -0.5773502691896258 1.0
  1.0836567383657543 -1.4608592996857799]]
